#!/bin/bash

set -e

# Parse image name for repo name and major tag version
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}
CurrVer=${IMAGE_NAME:tagStart:1}

#Tag also latest with passed build version (CurrVer)

# Tag and push image with passed version
echo "Tagging and pushing" ${repoName}:${CurrVer}
docker tag $IMAGE_NAME ${repoName}:${CurrVer}
docker push ${repoName}:${CurrVer}

# add  latest tag (this is not an automatic tag)
echo "Tagging and pushing" ${repoName}:latest
docker tag $IMAGE_NAME ${repoName}:latest
docker push ${repoName}:latest
