#!/bin/bash

set -e

# Parse image name for repo name and major tag version
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

#Read version from image
VERSIONS=$(docker run --rm  $IMAGE_NAME cat /var/opt/voxibot/voxibot.info|grep '=')
echo "/var/opt/voxibot/voxibot.info:"
echo $VERSIONS
VOXIBOT=$(echo "$VERSIONS"|sed -n 's/^VOXIBOT=\(.*\)/\1/p')

# Tag and push image with passed version
echo "Tagging and pushing" ${repoName}:${VOXIBOT}
docker tag $IMAGE_NAME ${repoName}:${VOXIBOT} || :
docker push ${repoName}:${VOXIBOT} || :

# add  latest tag (this is not an automatic tag)
echo "Tagging and pushing" ${repoName}:latest
docker tag $IMAGE_NAME ${repoName}:latest
docker push ${repoName}:latest
